[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.18.2"

[dev]
  command = "npm run dev"

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
